/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'glnie' at '6/27/16 10:10 AM' with Gradle 2.13
 *
 * @author glnie, @date 6/27/16 10:10 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
